"""Reading a repository at a pinned commit: filtering, language detection, and git objects."""

import pytest

from cqa.ingest.filters import skip_reason
from cqa.ingest.languages import detect_language
from cqa.ingest.walker import blob_sha, walk

from helpers import git


def test_blob_sha_matches_git():
    assert blob_sha(b"hello\n") == "ce013625030ba8dba906f756967f9e9ca394464a"


@pytest.mark.parametrize(
    "path, data, reason",
    [
        ("node_modules/left-pad/index.js", b"module.exports = 1\n", "denylisted_dir"),
        ("src/vendor/x.py", b"x = 1\n", "denylisted_dir"),
        ("package-lock.json", b"{}", "lockfile"),
        ("proto/api_pb2.py", b"# generated by protoc\n", "generated"),
        ("static/app.min.js", b"!function(){}", "generated"),
        ("logo.png", b"\x89PNG\r\n\x1a\n\x00\x00", "binary"),
        ("data/big.txt", b"a\n" * 20_001, "too_large"),
        ("schema.json", b"[" + b"0," * 30_000 + b"0]", "too_large"),
        ("gen/models.py", b"# Code generated by sqlc. DO NOT EDIT.\nx = 1\n", "generated"),
        ("src/app.py", b"print('hi')\n", None),
        ("README.md", b"# Title\n", None),
    ],
)
def test_skip_reason(path, data, reason):
    assert skip_reason(path, data) == reason


@pytest.mark.parametrize(
    "path, first_line, language",
    [
        ("src/app.py", "", "python"),
        ("bin/tool", "#!/usr/bin/env python3", "python"),
        ("README.md", "# Title", "markdown"),
        ("config/settings.yaml", "session:", "yaml"),
        ("Makefile", "all: build", None),
    ],
)
def test_detect_language(path, first_line, language):
    assert detect_language(path, first_line) == language


def test_walk_reads_git_objects_and_records_skips(toyrepo):
    repo, sha = toyrepo
    kept, skipped = walk(repo, sha)

    assert {s.path: s.reason for s in skipped} == {
        "poetry.lock": "lockfile",
        "vendor/leftpad.py": "denylisted_dir",
    }
    session = next(f for f in kept if f.path == "src/auth/session.py")
    assert session.language == "python"
    assert session.content_hash == git("rev-parse", f"{sha}:src/auth/session.py", cwd=repo)
    assert session.text.splitlines()[87].lstrip().startswith("def validate_token")
