"""Reading a repository at a pinned commit: filtering, language detection, and git objects."""

import subprocess

import pytest

from cqa.errors import IndexBuildError
from cqa.ingest import walker
from cqa.ingest.filters import MAX_BYTES, MAX_JSON_BYTES, MAX_LINES, count_lines, skip_reason
from cqa.ingest.languages import detect_language
from cqa.ingest.walker import blob_sha, clone_at, list_tree, walk

from helpers import git


def test_blob_sha_matches_git():
    assert blob_sha(b"hello\n") == "ce013625030ba8dba906f756967f9e9ca394464a"


@pytest.mark.parametrize(
    "path, data, reason",
    [
        ("node_modules/left-pad/index.js", b"module.exports = 1\n", "denylisted_dir"),
        ("src/vendor/x.py", b"x = 1\n", "denylisted_dir"),
        ("package-lock.json", b"{}", "lockfile"),
        ("proto/api_pb2.py", b"# generated by protoc\n", "generated"),
        ("static/app.min.js", b"!function(){}", "generated"),
        ("logo.png", b"\x89PNG\r\n\x1a\n\x00\x00", "binary"),
        ("data/big.txt", b"a\n" * (MAX_LINES + 1), "too_large"),
        ("data/long.txt", b"a\n" * MAX_LINES, None),
        ("src/huge.py", b"x" * (MAX_BYTES + 1), "too_large"),
        ("schema.json", b"[" + b"0," * (MAX_JSON_BYTES // 2) + b"0]", "too_large"),
        ("gen/models.py", b"# Code generated by sqlc. DO NOT EDIT.\nx = 1\n", "generated"),
        ("src/app.py", b"print('hi')\n", None),
        ("README.md", b"# Title\n", None),
    ],
)
def test_skip_reason(path, data, reason):
    assert skip_reason(path, data) == reason


@pytest.mark.parametrize(
    "path, first_line, language",
    [
        ("src/app.py", "", "python"),
        ("bin/tool", "#!/usr/bin/env python3", "python"),
        ("README.md", "# Title", "markdown"),
        ("config/settings.yaml", "session:", "yaml"),
        ("Makefile", "all: build", None),
    ],
)
def test_detect_language(path, first_line, language):
    assert detect_language(path, first_line) == language


def test_walk_reads_git_objects_and_records_skips(toyrepo):
    repo, sha = toyrepo
    kept, skipped = walk(repo, sha)

    assert {s.path: s.reason for s in skipped} == {
        "poetry.lock": "lockfile",
        "vendor/leftpad.py": "denylisted_dir",
    }
    session = next(f for f in kept if f.path == "src/auth/session.py")
    assert session.language == "python"
    assert session.content_hash == git("rev-parse", f"{sha}:src/auth/session.py", cwd=repo)
    assert session.text.splitlines()[87].lstrip().startswith("def validate_token")


def commit_all(repo, message="change"):
    git("add", "-A", cwd=repo)
    git("commit", "-q", "-m", message, cwd=repo)
    return git("rev-parse", "HEAD", cwd=repo)


def test_count_lines():
    assert count_lines(b"") == 0
    assert count_lines(b"a\nb") == count_lines(b"a\nb\n") == 2


@pytest.mark.parametrize(
    "path, first_line, language",
    [
        ("bin/tool", "#!/usr/bin/env -S python3 -u", "python"),
        ("bin/run", "#!/bin/sh", None),
        ("A.PY", "", "python"),
    ],
)
def test_detect_language_edge_cases(path, first_line, language):
    assert detect_language(path, first_line) == language


def test_list_tree_skips_symlinks_and_submodules(toyrepo):
    repo, _ = toyrepo
    (repo / "link.py").symlink_to("src/auth/session.py")
    sub = repo / "sub"
    sub.mkdir()
    git("init", "-q", cwd=sub)
    (sub / "x.py").write_text("x = 1\n")
    commit_all(sub)
    paths = {p for p, _ in list_tree(repo, commit_all(repo))}
    assert "src/auth/session.py" in paths
    assert "link.py" not in paths and "sub" not in paths


def test_walk_does_not_read_path_skipped_or_oversized_files(toyrepo, monkeypatch):
    repo, sha = toyrepo
    requested = []
    real_read = walker.read_blobs
    monkeypatch.setattr(walker, "read_blobs", lambda d, shas: requested.extend(shas) or real_read(d, shas))
    monkeypatch.setattr("cqa.ingest.filters.MAX_BYTES", 1000)
    kept, skipped = walk(repo, sha)
    reasons = {s.path: s.reason for s in skipped}
    assert reasons["vendor/leftpad.py"] == "denylisted_dir"
    assert reasons["src/auth/session.py"] == "too_large"
    skipped_shas = {
        s.content_hash for s in skipped if s.reason in ("denylisted_dir", "lockfile", "too_large")
    }
    assert skipped_shas and not skipped_shas & set(requested)
    assert all(f.content_hash in requested for f in kept)


def test_walk_enforces_the_repository_limits(toyrepo, monkeypatch):
    repo, sha = toyrepo
    monkeypatch.setattr(walker, "MAX_CLONE_BYTES", 10)
    with pytest.raises(IndexBuildError, match="byte limit"):
        walk(repo, sha)
    monkeypatch.setattr(walker, "MAX_CLONE_BYTES", 10**9)
    monkeypatch.setattr(walker, "MAX_REPO_LINES", 10)
    with pytest.raises(IndexBuildError, match="line limit"):
        walk(repo, sha)


def test_walk_of_an_unknown_commit_is_an_index_build_error(toyrepo):
    repo, _ = toyrepo
    with pytest.raises(IndexBuildError):
        walk(repo, "0" * 40)


def test_clone_at_requires_a_full_sha(tmp_path):
    with pytest.raises(ValueError, match="40-character"):
        clone_at("https://example.com/r.git", "abc123", tmp_path / "dest")


@pytest.mark.parametrize(
    "url",
    ["ext::sh -c touch% /tmp/pwned", "file:///etc", "http://example.com/r.git", "git@example.com:a/b.git"],
)
def test_clone_at_refuses_every_transport_but_https(url, tmp_path):
    with pytest.raises(ValueError, match="https"):
        clone_at(url, "a" * 40, tmp_path / "dest")
    assert not (tmp_path / "dest").exists()


def test_clone_at_uses_a_local_repository_in_place(toyrepo, tmp_path):
    repo, sha = toyrepo
    assert clone_at(str(repo), sha, tmp_path / "unused") == repo
    assert not (tmp_path / "unused").exists()


def test_clone_at_reuses_a_fetch_that_holds_the_commit(toyrepo, tmp_path):
    repo, sha = toyrepo
    dest = tmp_path / "fetched"
    dest.mkdir()
    git("init", "-q", cwd=dest)
    git("fetch", "-q", str(repo), sha, cwd=dest)
    assert clone_at("https://unreachable.invalid/r.git", sha, dest) == dest


def test_clone_at_fetches_one_commit_over_https_only(tmp_path, monkeypatch):
    calls = []

    def fake_run(cmd, **kwargs):
        calls.append((cmd, kwargs))
        return subprocess.CompletedProcess(cmd, 0, b"", b"")

    monkeypatch.setattr(walker.subprocess, "run", fake_run)
    url, sha = "https://example.com/r.git", "b" * 40
    clone_at(url, sha, tmp_path / "dest")
    fetch, kwargs = calls[-1]
    assert "fetch" in fetch and fetch[-3:] == ["--", url, sha]
    assert {"protocol.allow=never", "protocol.https.allow=always", "--no-recurse-submodules"} <= set(fetch)
    assert kwargs["timeout"] == walker.CLONE_TIMEOUT_S
    assert kwargs["env"]["GIT_TERMINAL_PROMPT"] == "0" and kwargs["env"]["GIT_LFS_SKIP_SMUDGE"] == "1"


def test_clone_at_timeout_is_an_index_build_error(tmp_path, monkeypatch):
    def fake_run(cmd, **kwargs):
        if "fetch" in cmd:
            raise subprocess.TimeoutExpired(cmd, kwargs["timeout"])
        return subprocess.CompletedProcess(cmd, 0, b"", b"")

    monkeypatch.setattr(walker.subprocess, "run", fake_run)
    with pytest.raises(IndexBuildError, match="timed out"):
        clone_at("https://example.com/r.git", "c" * 40, tmp_path / "dest")
